### ISSUE TITLE
Python kernel crashing during placefield detection

### ISSUE THREAD

**Issue by horsto** [kavli-ntnu/opexebo#12]
This is more for reference and not an actual problem with the opexebo code.
Lately I have been running a lot of data through opexebo and noticed seemingly random python crashes (kernel restarts automatically in notebooks or things crash completely). 
numpy: 1.16.4 
scipy: 1.15.4 
skimage: 0.15.0 

I finally pinpointed the problem to placeField.py `fmap = morphology.reconstruction(Ie, firing_map) `. On a ratemap example this line of code failed stochastically (!) and caused python crashes. The stochastic nature of this error is super strange to me and I am struggling to find the cause. If executed in a loop, this statement (with the same input) fails after 1-10 times of execution.

**Comment by horsto** [comment]
https://github.com/scikit-image/scikit-image/issues/4078

**Comment by simon-ball** [comment]
The additional NaN detection and replacement in v0.3.0 should have resolved this

**Comment by horsto** [comment]
Thanks! I’ll check it.
