### ISSUE TITLE
Matplotlib vers in requirements

### ISSUE THREAD

**Issue by horsto** [kavli-ntnu/opexebo#14]
Installing opexebo always deletes my current matplotlib version and overwrites it with an older version. Is it possible to raise the version of matplotlib in the requirements?

**Comment by simon-ball** [comment]
Will fix in next release: matplotlib can move to `dev-requirements`, since it's only used in the tests (and in the extensive debug information in gridscore)

**Comment by simon-ball** [comment]
Fixed in release  0.3.0
