### ISSUE TITLE
Non-square arenas

### ISSUE THREAD

**Issue by simon-ball** [kavli-ntnu/opexebo#4]
All test cases so far have used square arenas, typically 80cm x 80cm. Performance with linear, circular, and rectangular cases are unknown - autocorrelation and gridscore is a particular issue here

**Comment by horsto** [comment]
Preliminary testing has been done on _rectangular_ test cases for autocorrelation and gridscore. Seems to work fine.

**Comment by simon-ball** [comment]
Confirmed, rectangular non-square arenas seem fully functional. Don't (yet) have a compatible dataset for testing circular arenas.
