### ISSUE TITLE
Speed score

### ISSUE THREAD

**Issue by simon-ball** [kavli-ntnu/opexebo#6]
Speed score values calculated within opexebo are largely uncorrelated with values calculated via BNT's ScreeningByTemplate.

Two probable causes for this:
* `opexebo.analysis.speedscore` is implemented based on BNT's `+scripts.speedScore`, while the values being tested on are output by the _independent_ speed score routine in BNT's ScreeningBytemplate -> test like for like against `score15`, `score16` from the relevant BNT script
* I'm not convinced that the correlation method used in Python (`numpy.corrcoef`) is equivalent to that in Matlab (`corr`) - investigate scipy alternatives

**Comment by simon-ball** [comment]
Secondary note: the test data so far is not curated; it's a random mixture of cells. A curated set of cells that do include some strong border cells would be useful (also relevant for #5, #7)

**Comment by fralik** [comment]
Just a quick note here :-) `+scripts.speedScore` is more up-to-date with what researchers need(ed). I think there was a comment in the Wiki that one shall not use speed score from `screeningByTemplate`.

**Comment by simon-ball** [comment]
Provisionally fixed in #29
